---
title: "Wild git collaboration practice!"
author: "your names here!"
date: "1/25/2022"
format:
  html:
    embed-resources: true
execute:
  echo: true
  message: false
  warning: false
---

```{r setup}
library(tidyverse)
```

## STEP 5: No merge conflicts!

```{r partner 1}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a plot of price vs. carat (or some other
### variables of your choice)

ggplot(diamonds)+
  geom_point(aes(x=carat,y=price))

```

```{r partner 2}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a subset based on filtering, e.g., 
### size greater than 1 carat or cut is "Ideal"

ggplot(diamonds, aes(x = carat, y = cut)) +
  geom_point()
  

```

## STEP 7: Uh oh, merge conflicts!

```{r break-it-1}
diamonds |> 
  group_by(carat) |> 
  summarize(mean=mean())


ggplot(diamonds, aes(x = carat, y = table)) +
  geom_point()


```

## STEP 11: And even more merge conflicts!

```{r break-it-2}
### Both partners - delete this comment, then write some code here
### to plot, summarize, calculate something simple using the diamonds
### dataset.


```
